# Generated by Django 5.1.3 on 2024-11-29 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(help_text='Name of the purchased item', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the purchased item', max_digits=10)),
                ('weight', models.FloatField(blank=True, help_text='Weight in kilograms (if applicable)', null=True)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of items purchased')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('food_item_type', models.CharField(choices=[('raw_material', 'Raw Material'), ('restaurant_menu', 'Restaurant Menu'), ('packaged_food', 'Packaged Food')], help_text='Type of food item being sold', max_length=50)),
                ('food_item_id', models.PositiveIntegerField(help_text='ID of the sold food item')),
                ('food_item_name', models.CharField(help_text='Name of the sold food item', max_length=255)),
                ('quantity', models.FloatField(help_text='Quantity sold (kg or units)')),
                ('price', models.DecimalField(decimal_places=2, help_text='Total price', max_digits=10)),
                ('transaction_id', models.CharField(help_text='Payment Gateway Transaction ID', max_length=100, unique=True)),
                ('order_id', models.CharField(help_text='Payment Gateway Order ID', max_length=100, unique=True)),
                ('signature', models.CharField(help_text='Payment Gateway signature ID', max_length=100, unique=True)),
                ('payment_method', models.CharField(choices=[('upi', 'UPI'), ('paypal', 'PayPal'), ('card', 'Credit/Debit Card')], help_text='Payment method used', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Transaction status', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
