# Generated by Django 5.1.3 on 2024-12-01 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='price',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_id',
            new_name='payment_id',
        ),
    ]
