# Generated by Django 5.1.3 on 2024-12-01 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='food_item_id',
            field=models.CharField(help_text='Name of the sold food item', max_length=255),
        ),
    ]
