# Generated by Django 5.1.3 on 2024-12-02 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_appuser_options_alter_client_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='username',
        ),
    ]
