# Generated by Django 5.1.3 on 2024-11-29 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterial',
            name='humidity',
            field=models.FloatField(blank=True, help_text='Humidity in %', null=True),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='microbial_count',
            field=models.PositiveIntegerField(blank=True, help_text='Microbial count in CFU/g', null=True),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='pH',
            field=models.FloatField(blank=True, help_text='pH levels', null=True),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='temperature',
            field=models.FloatField(blank=True, help_text='Temperature in °C', null=True),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='weight',
            field=models.FloatField(blank=True, help_text='Weight in kilograms', null=True),
        ),
    ]
