# Generated by Django 5.1.3 on 2024-11-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_alter_rawmaterial_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantmenu',
            name='ingredients',
            field=models.ManyToManyField(blank=True, null=True, related_name='menus', to='stock.rawmaterial'),
        ),
        migrations.AlterField(
            model_name='restaurantmenu',
            name='price_per_serving',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per serving', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='restaurantmenu',
            name='serving_size',
            field=models.FloatField(blank=True, help_text='Serving size in kilograms', null=True),
        ),
        migrations.AlterField(
            model_name='restaurantmenu',
            name='temperature',
            field=models.FloatField(blank=True, help_text='Ideal serving temperature in °C', null=True),
        ),
        migrations.AlterField(
            model_name='restaurantmenu',
            name='total_weight',
            field=models.FloatField(blank=True, help_text='Total prepared weight in kilograms', null=True),
        ),
    ]
