# Generated by Django 5.1.3 on 2024-12-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_alter_restaurantmenu_ingredients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantmenu',
            name='donate',
            field=models.BooleanField(blank=True, default=False, help_text='Mark as donated', null=True),
        ),
    ]
