# Generated by Django 5.1.3 on 2024-12-01 11:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_restaurantmenu_donate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantmenu',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
