# Generated by Django 5.1.3 on 2024-11-29 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagedfoodorder',
            name='packaged_food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.packagedfood'),
        ),
        migrations.AddField(
            model_name='order',
            name='packaged_food_items',
            field=models.ManyToManyField(through='orders.PackagedFoodOrder', to='stock.packagedfood'),
        ),
        migrations.AddField(
            model_name='restaurantfoodorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
        migrations.AddField(
            model_name='restaurantfoodorder',
            name='restaurant_menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.restaurantmenu'),
        ),
        migrations.AddField(
            model_name='order',
            name='restaurant_menu_items',
            field=models.ManyToManyField(through='orders.RestaurantFoodOrder', to='stock.restaurantmenu'),
        ),
    ]
